
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-srv-deployment
  labels:
    app : cwebserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app : cwebserver
  template:
    metadata:
      labels:
        app : cwebserver
    spec:
      containers:
      - name: ws
        image: gcr.io/lucky-outpost-354817/npr_proxy_service:v2.1
        imagePullPolicy: Always

        ports:
        - containerPort: 80
          protocol: TCP
        
        livenessProbe:
          httpGet:
            path: /live
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: cwebserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80